# Carga y Limpieza de Datos

In [1]:
# Importo paquetes

import numpy as np
import pandas as pd
import seaborn as sn
import matplotlib.pyplot as plt
%matplotlib inline

from scipy import sparse

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import LatentDirichletAllocation as LDA
from sklearn.decomposition import NMF
from sklearn.feature_extraction import text 

In [2]:
X_train = sparse.load_npz("./Data/X_train_Tf-idf.npz")
X_test = sparse.load_npz("./Data/X_test_Tf-idf.npz")
y_train = pd.read_csv("./Data/y_train.csv", header=None)
y_test = pd.read_csv("./Data/y_test.csv", header=None)

In [3]:
lda_model = LDA(n_components=6, max_iter=5, verbose=5)
nmf_model = NMF(n_components=10, max_iter=10, verbose=5)

# LDA

In [4]:
# train a LDA Model
lda_model = LDA(n_components=10, max_iter=10, verbose=5)
X_train_LDA = lda_model.fit_transform(X_train, y_train)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  1.8min remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  1.8min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


iteration: 1 of max_iter: 10


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  1.7min remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  1.7min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


iteration: 2 of max_iter: 10


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  1.6min remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  1.6min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


iteration: 3 of max_iter: 10


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  1.4min remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  1.4min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


iteration: 4 of max_iter: 10


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  1.3min remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  1.3min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


iteration: 5 of max_iter: 10


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  1.3min remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  1.3min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


iteration: 6 of max_iter: 10


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  1.2min remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  1.2min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


iteration: 7 of max_iter: 10


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  1.2min remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  1.2min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


iteration: 8 of max_iter: 10


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  1.2min remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  1.2min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


iteration: 9 of max_iter: 10


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  1.2min remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  1.2min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


iteration: 10 of max_iter: 10


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:   52.7s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:   52.7s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:   56.9s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:   56.9s finished


TypeError: transform() takes 2 positional arguments but 3 were given

In [10]:
X_test_LDA = lda_model.transform(X_test)
topic_word = lda_model.components_

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:   24.2s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:   24.2s finished


In [11]:
X_train_LDA

array([[0.01512354, 0.01512328, 0.86387883, ..., 0.01512322, 0.01512445,
        0.0151235 ],
       [0.02922721, 0.73686297, 0.02922969, ..., 0.02922967, 0.02924127,
        0.02928272],
       [0.0257056 , 0.02570557, 0.02570428, ..., 0.0257288 , 0.28480319,
        0.02570393],
       ...,
       [0.04143262, 0.04143875, 0.0414343 , ..., 0.04143361, 0.04145208,
        0.04143097],
       [0.03693076, 0.66758091, 0.03692876, ..., 0.03692848, 0.03694035,
        0.03692716],
       [0.02500811, 0.10806087, 0.0250074 , ..., 0.02500811, 0.19263691,
        0.23738484]])

In [12]:
topic_word

array([[60.13568325,  5.30741598,  0.10000234, ..., 11.7507594 ,
         0.10000829,  0.1       ],
       [ 0.10001184,  0.1000025 ,  0.1       , ...,  0.1       ,
         0.1       ,  0.10000051],
       [14.5266005 ,  0.23060819,  0.1       , ...,  0.10000109,
         0.1       ,  0.1       ],
       ...,
       [17.66624602,  0.10000463, 18.18807109, ...,  0.1       ,
         0.1       ,  0.1       ],
       [54.27730461,  0.10002596,  0.1       , ...,  0.10000277,
        14.20644085, 14.16152315],
       [ 0.10000142,  0.10000028,  0.10000003, ...,  0.10000067,
         0.1       ,  0.10000011]])

In [13]:
X_train_lda = pd.DataFrame(X_train_LDA)
X_test_lda = pd.DataFrame(X_test_LDA)

In [14]:
X_train_lda.to_csv("./Data/X_train_LDA.csv", index=False )
X_test_lda.to_csv("./Data/X_test_LDA.csv", index=False )

# NMF

In [15]:
# train a NFD Model
nmf_model = NMF(n_components=10, max_iter=10, verbose=5)
X_train_NMF = nmf_model.fit_transform(X_train, y_train)

# view the topic models
'''n_top_words = 10
topic_summaries = []
for i, topic_dist in enumerate(topic_word):
    topic_words = numpy.array(vocab)[numpy.argsort(topic_dist)][:-(n_top_words+1):-1]
    topic_summaries.append(' '.join(topic_words))'''

violation: 1.0
violation: 0.07144838951380783
violation: 0.016124225567820793
violation: 0.008061802390952097
violation: 0.004769969869043397
violation: 0.0030315973238454904
violation: 0.002020569964912353
violation: 0.0013952113111662344
violation: 0.0009876929690949133
violation: 0.000710498714985069


"n_top_words = 10\ntopic_summaries = []\nfor i, topic_dist in enumerate(topic_word):\n    topic_words = numpy.array(vocab)[numpy.argsort(topic_dist)][:-(n_top_words+1):-1]\n    topic_summaries.append(' '.join(topic_words))"

In [16]:
X_test_NMF = nmf_model.transform(X_test)
topic_word = nmf_model.components_ 

violation: 1.0
violation: 0.0008544384754688434
violation: 1.2973705087951626e-06
Converged at iteration 3


In [17]:
X_train_NMF

array([[2.02886633e-06, 3.22114672e-06, 5.54931862e-06, ...,
        4.27455147e-04, 1.27847003e-03, 2.75179071e-04],
       [4.13391374e-06, 1.15960027e-05, 1.08139516e-05, ...,
        1.12094741e-04, 3.99712509e-04, 5.43445395e-05],
       [5.18900470e-07, 2.87781056e-06, 4.03957056e-06, ...,
        6.12724740e-04, 3.33763051e-03, 8.99652019e-05],
       ...,
       [1.09308105e-07, 0.00000000e+00, 2.36938775e-07, ...,
        1.63890039e-05, 1.79347393e-05, 1.22861913e-05],
       [5.65106375e-07, 1.37620358e-06, 1.57602193e-06, ...,
        2.54979280e-05, 9.38879361e-05, 9.49712497e-06],
       [2.21511039e-06, 2.10267237e-06, 9.24313429e-06, ...,
        4.80176598e-04, 1.72005784e-03, 2.03651010e-04]])

In [18]:
X_train_nmf = pd.DataFrame(X_train_NMF)
X_test_nmf = pd.DataFrame(X_test_NMF)

In [19]:
X_train_nmf.to_csv("./Data/X_train_NMF.csv", index=False )
X_test_nmf.to_csv("./Data/X_test_NMF.csv", index=False )