# Carga y Limpieza de Datos

In [1]:
# Importo paquetes

import numpy as np
import pandas as pd
import seaborn as sn
import matplotlib.pyplot as plt
%matplotlib inline

from scipy import sparse

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import LatentDirichletAllocation as LDA
from sklearn.decomposition import NMF
from sklearn.feature_extraction import text 

In [2]:
X_train = sparse.load_npz("./Data/X_train_Tf-idf.npz")
X_test = sparse.load_npz("./Data/X_test_Tf-idf.npz")
y_train = pd.read_csv("./Data/y_train.csv", header=None)
y_test = pd.read_csv("./Data/y_test.csv", header=None)

# LDA

In [3]:
# train a LDA Model
lda_model = LDA(n_components=200, max_iter=10, verbose=5)
X_train_LDA = lda_model.fit_transform(X_train, y_train)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  3.0min remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  3.0min finished


iteration: 1 of max_iter: 10


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  3.3min remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  3.3min finished


iteration: 2 of max_iter: 10


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  3.2min remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  3.2min finished


iteration: 3 of max_iter: 10


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  3.0min remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  3.0min finished


iteration: 4 of max_iter: 10


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  2.8min remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  2.8min finished


iteration: 5 of max_iter: 10


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  2.8min remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  2.8min finished


iteration: 6 of max_iter: 10


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  2.7min remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  2.7min finished


iteration: 7 of max_iter: 10


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  3.0min remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  3.0min finished


iteration: 8 of max_iter: 10


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  3.1min remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  3.1min finished


iteration: 9 of max_iter: 10


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  2.9min remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  2.9min finished


iteration: 10 of max_iter: 10


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  1.7min remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  1.7min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  1.5min remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  1.5min finished


In [4]:
X_test_LDA = lda_model.transform(X_test)
topic_word = lda_model.components_

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:   40.9s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:   40.9s finished


In [5]:
X_train_LDA

array([[0.00075615, 0.66504679, 0.00075615, ..., 0.00075615, 0.00075615,
        0.00075615],
       [0.00146126, 0.00146126, 0.00146126, ..., 0.00146126, 0.00146126,
        0.00146126],
       [0.00128515, 0.00128515, 0.00128515, ..., 0.00128515, 0.00128515,
        0.00128515],
       ...,
       [0.00207155, 0.00207155, 0.00207155, ..., 0.00207155, 0.00207155,
        0.00207155],
       [0.00184636, 0.00184636, 0.00184636, ..., 0.00184636, 0.00184636,
        0.00184636],
       [0.00125027, 0.00125027, 0.00125027, ..., 0.00125027, 0.00125027,
        0.00125027]])

In [6]:
topic_word

array([[5.00000000e-03, 5.00000000e-03, 5.00000000e-03, ...,
        5.00000000e-03, 5.00000000e-03, 5.00000000e-03],
       [5.00000000e-03, 5.00000000e-03, 5.00000000e-03, ...,
        5.00000000e-03, 5.00000000e-03, 5.00000000e-03],
       [9.29407589e+00, 5.00000000e-03, 1.02466727e+01, ...,
        5.00000000e-03, 5.00000000e-03, 5.00000000e-03],
       ...,
       [5.00000000e-03, 5.00000000e-03, 5.00000000e-03, ...,
        5.00000000e-03, 5.00000000e-03, 5.00000000e-03],
       [5.00000000e-03, 5.00000000e-03, 5.00000000e-03, ...,
        5.00000000e-03, 5.00000000e-03, 5.00000000e-03],
       [5.00000000e-03, 5.00000000e-03, 5.00000000e-03, ...,
        5.00000000e-03, 5.00000000e-03, 5.00000000e-03]])

In [7]:
X_train_lda = pd.DataFrame(X_train_LDA)
X_test_lda = pd.DataFrame(X_test_LDA)

In [8]:
X_train_lda.to_csv("./Data/X_train_LDA.csv", index=False )
X_test_lda.to_csv("./Data/X_test_LDA.csv", index=False )

# NMF

In [9]:
# train a NFD Model
nmf_model = NMF(n_components=200, max_iter=10, verbose=5)
X_train_NMF = nmf_model.fit_transform(X_train, y_train)

# view the topic models
'''n_top_words = 10
topic_summaries = []
for i, topic_dist in enumerate(topic_word):
    topic_words = numpy.array(vocab)[numpy.argsort(topic_dist)][:-(n_top_words+1):-1]
    topic_summaries.append(' '.join(topic_words))'''

violation: 1.0
violation: 0.09650842740112399
violation: 0.03809096084104863
violation: 0.026642340371176073
violation: 0.02084609256243121
violation: 0.011216446975074259
violation: 0.007103333142906282
violation: 0.005421083016663972
violation: 0.0044097189837288145
violation: 0.0037037849246204734


"n_top_words = 10\ntopic_summaries = []\nfor i, topic_dist in enumerate(topic_word):\n    topic_words = numpy.array(vocab)[numpy.argsort(topic_dist)][:-(n_top_words+1):-1]\n    topic_summaries.append(' '.join(topic_words))"

In [10]:
X_test_NMF = nmf_model.transform(X_test)
topic_word = nmf_model.components_ 

violation: 1.0
violation: 0.022921538461794774
violation: 0.0006274693787449077
violation: 3.72828142736053e-05
Converged at iteration 4


In [11]:
X_train_NMF

array([[0.00000000e+00, 0.00000000e+00, 3.41045292e-07, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 3.90596414e-07, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [2.40060302e-07, 4.62128737e-07, 4.75285425e-07, ...,
        3.82253529e-04, 0.00000000e+00, 0.00000000e+00],
       [2.63117648e-07, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [12]:
X_train_nmf = pd.DataFrame(X_train_NMF)
X_test_nmf = pd.DataFrame(X_test_NMF)

In [13]:
X_train_nmf.to_csv("./Data/X_train_NMF.csv", index=False )
X_test_nmf.to_csv("./Data/X_test_NMF.csv", index=False )